locale: fr_FR
title: SoliCode
description: SoliCode est une école de codage à Tanger
baseurl: "/site-web"
permalink: /:title/
url: "https://solicode.co"
include: ["_pages"]
environment: production
destination: docs
excerpt_separator: <!-- end introduction -->

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-sitemap

# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

# Pagination 
paginate: 6
paginate_path: /page:num/


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - docs

collections:
  activities:
    output: true
  slides:
   output: false


